# Generated by Django 4.2.dev20220603193729 on 2022-06-15 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_aboutme_body_alter_contact_message_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True)),
                ('thumbnail', models.ImageField(null=True, upload_to='')),
                ('price', models.IntegerField(null=True)),
                ('description', models.TextField(null=True)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='aboutMe',
            new_name='about',
        ),
        migrations.RenameModel(
            old_name='mySkills',
            new_name='mySkill',
        ),
        migrations.DeleteModel(
            name='services',
        ),
    ]
