# Generated by Django 4.2.dev20220603193729 on 2022-06-15 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_about_body_alter_contact_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='myskill',
            name='skills',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
