# Generated by Django 4.2.dev20220603193729 on 2022-06-15 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_myskill_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='myskill',
            name='thumbnail',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
